# Generated by Django 3.1.7 on 2021-08-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210811_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='ProfileImage',
            new_name='img',
        ),
    ]
