# Generated by Django 3.1.7 on 2021-08-12 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20210812_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Eye Surgery', 'Eye Surgery'), ('General Surgery', 'General Surgery'), ('Dentist', 'Dentist'), ('Physician', 'Physician')], max_length=200)),
                ('date_app', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.blog')),
            ],
        ),
    ]
