# Generated by Django 3.1.7 on 2021-08-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20210812_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='timings',
            field=models.CharField(choices=[('10:00 AM - 10:45 AM', '10:00 AM - 10:45 AM'), ('12:00 PM - 12:45 PM', '12:00 PM - 12:45 PM'), ('02:30 PM - 03:15 PM', '02:30 PM - 03:15 PM'), ('04:15 PM - 05:00 PM', '04:15 PM - 05:00 PM')], max_length=200, null=True),
        ),
    ]
