# Generated by Django 3.1.7 on 2021-08-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_appointment_tp_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='tp_manager',
            new_name='Doctor',
        ),
    ]
